SELECT
B.BOOK_NUM,
B.BOOK_TITLE,
B.BOOK_SUBJECT,
ROUND(AVG_COST, 2) AS AVGCOST,
ROUND(B.BOOK_COST - AVG_COST, 2) AS DIFFERENCE
FROM
BOOK B
JOIN (
SELECT
BOOK_SUBJECT,
AVG(BOOK_COST) AS AVG_COST
FROM
BOOK
GROUP BY
BOOK_SUBJECT
) AS SUBJ_AVG ON B.BOOK_SUBJECT = SUBJ_AVG.BOOK_SUBJECT
ORDER BY
B.BOOK_TITLE;