SELECT
ROUND(MIN(AVG_COST), 2) AS "Lowest Avg Cost",
ROUND(MAX(AVG_COST), 2) AS "Highest Avg Cost"
FROM (
SELECT
BOOK_SUBJECT,
AVG(BOOK_COST) AS AVG_COST
FROM
BOOK
GROUP BY
BOOK_SUBJECT
) AS SUBJECT_AVERAGES;