SELECT
INVOICE.CUS_CODE,
CUSTOMER.CUS_BALANCE,
CONVERT(Sum(LINE.LINE_UNITS*LINE.LINE_PRICE), DECIMAL(10,2)) AS "Total Purchases",
COUNT(LINE.INV_NUMBER) AS "Number of Purchases",
ROUND(AVG(LINE.LINE_UNITS*LINE.LINE_PRICE), 2) AS "Average Purchase Amount"
FROM
CUSTOMER,
INVOICE,
LINE
WHERE
CUSTOMER.CUS_CODE=INVOICE.CUS_CODE
AND
INVOICE.INV_NUMBER=LINE.INV_NUMBER
GROUP BY
INVOICE.CUS_CODE,
CUSTOMER.CUS_BALANCE
ORDER BY
INVOICE.CUS_CODE;