SELECT
CUSTOMER.CUS_CODE,
COUNT(DISTINCT INVOICE.INV_NUMBER) AS "Number of Invoices",
ROUND(SUM(LINE.LINE_UNITS*LINE.LINE_PRICE), 2) AS "Total Customer Purchases"
FROM
CUSTOMER
JOIN
INVOICE INVOICE ON CUSTOMER.CUS_CODE=INVOICE.CUS_CODE
JOIN
LINE LINE ON INVOICE.INV_NUMBER=LINE.INV_NUMBER
GROUP BY
CUSTOMER.CUS_CODE;