SELECT
INVOICE.CUS_CODE,
LINE.INV_NUMBER,
ROUND(SUM(LINE.LINE_UNITS*LINE.LINE_PRICE), 2) AS "Invoice Total"
FROM
INVOICE,
LINE
WHERE
INVOICE.INV_NUMBER=LINE.INV_NUMBER
GROUP BY
INVOICE.CUS_CODE,
LINE.INV_NUMBER
ORDER BY
INVOICE.CUS_CODE;