INSERT INTO EMP_1 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
SELECT
    EMP_NUM,
    EMP_LNAME,
    EMP_FNAME,
    EMP_INITIAL,
    EMP_HIREDATE,
    JOB_CODE
FROM
    EMPLOYEE
WHERE
    EMP_NUM IN ('103', '104', '105', '106', '107', '108', '109')
ON DUPLICATE KEY UPDATE
    EMP_LNAME = VALUES(EMP_LNAME), -- Update last name if duplicate
    EMP_FNAME = VALUES(EMP_FNAME), -- Update first name if duplicate
    EMP_INITIAL = VALUES(EMP_INITIAL),
    EMP_HIREDATE = VALUES(EMP_HIREDATE),
    JOB_CODE = VALUES(JOB_CODE);